### ISSUE TITLE
Suport DevServerBuilder

### ISSUE THREAD

**Issue by lucasteles** [meltedspark/angular-cli-builders#5]
Would be cool if you provide a wrapper of "@angular-devkit/build-angular:dev-server", for run a custom webpack on ng serve

**Comment by meltedspark** [comment]
I will look into that. Meanwhile as a workaround you can use `ng build --watch` instead of `ng serve`. This is slower but does the work.

**Comment by httpete** [comment]
this was exactly what I was looking for - I thought that because we replaced the browser build target ng serve would pick that up - doesn't seem to.

**Comment by meltedspark** [comment]
Implemented in `2.1.0`
